Server:
  port: 60019
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

file:
  dir:
    record: /home/t23304/record/
    image: /home/t23304/image/

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    livereload:
      enabled: true