Server:
  port: 60019
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

file:
  dir:
    record: /home/t23304/record/
    image: /home/t23304/image/

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/db23304
    username: dbid233
    password: dbpass233
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        ddl-auto: create
#    open-in-view: false

  devtools:
    livereload:
      enabled: true